on:
  schedule:
    - cron: '0 0 * * 1' #every monday at 00:00
  workflow_dispatch:


jobs:
  update-genesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update genesis file for test network
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/idunion/indy-genesis-updater/indy-genesis-updater
          options: -v ${{ github.workspace }}/genesis-idunion:/app/genesis/
          run: /app/indy-genesis-updater -g /app/genesis/pool-idunion-test -o /app/genesis/pool-idunion-test
      - name: Update genesis file for test network
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/idunion/indy-genesis-updater/indy-genesis-updater
          options: -v ${{ github.workspace }}/genesis-idunion:/app/genesis/
          run: /app/indy-genesis-updater -g /app/genesis/pool-idunion-mvp -o /app/genesis/pool-idunion-mvp
      - name: Push changes to github
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No Changes"
          else
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add ./genesis-idunion
            git commit -m "Updating genesis files"
            git push